package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	graph "github.com/praadit/dikurium-test/pkg/graph/generated"
	"github.com/praadit/dikurium-test/pkg/models"
)

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *models.Todo) (*models.User, error) {
	r.Loader.UserByTodo.ClearAll()
	thunk := r.Loader.UserByTodo.Load(ctx, obj.UserID)

	user, err := thunk()
	if err != nil {
		return nil, err
	}

	return user, nil
}

// Todo returns graph.TodoResolver implementation.
func (r *Resolver) Todo() graph.TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
