package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	graph "github.com/praadit/dikurium-test/pkg/graph/generated"
	"github.com/praadit/dikurium-test/pkg/models"
)

// Todo is the resolver for the todo field.
func (r *queryResolver) Todo(ctx context.Context) ([]*models.Todo, error) {
	return r.Controller.Todos(ctx)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
