package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/praadit/dikurium-test/pkg/models"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input models.SignupInput) (*models.SignupResult, error) {
	return r.Controller.Signup(ctx, &input)
}

// SignIn is the resolver for the signIn field.
func (r *mutationResolver) SignIn(ctx context.Context, input models.SigninInput) (*models.SigninResult, error) {
	return r.Controller.Signin(ctx, &input)
}
