package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	graph "github.com/praadit/dikurium-test/pkg/graph/generated"
	"github.com/praadit/dikurium-test/pkg/models"
)

// Todo is the resolver for the todo field.
func (r *userResolver) Todo(ctx context.Context, obj *models.User) ([]*models.Todo, error) {
	r.Loader.TodoByUser.ClearAll()
	thunk := r.Loader.TodoByUser.Load(ctx, obj.ID)

	todos, err := thunk()
	if err != nil {
		return nil, err
	}

	return todos, nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
