[debug]
PORT="8080"
DB_HOST="localhost"
DB_PORT="5432"
DB_USER="postgres"
DB_PASS="password"
DB_TLS=false
DB_NAME="dikurium-db"
API_SECRET="secret"

[local]
PORT="8080"
DB_HOST="localhost"
DB_PORT="5432"
DB_USER="postgres"
DB_PASS="password"
DB_TLS=false
DB_NAME="dikurium-db"
API_SECRET="secret"